
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PcPool.DataAccessLayer.PcPoolDBaseModel
{

using System;
    using System.Collections.Generic;
    
public partial class DeviceInstance
{

    public int DeviceInstanceId { get; set; }

    public Nullable<int> ManufacturingYear { get; set; }

    public string SeriaNo { get; set; }

    public string RFID { get; set; }

    public string DescriptionTitle { get; set; }

    public string Description { get; set; }

    public Nullable<int> DeviceStatusId { get; set; }

    public int DeviceTypeId { get; set; }

}

}
