//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PcPool.DataAccessLayer.PcPoolDBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceType
    {
        public DeviceType()
        {
            this.DeviceInstances = new HashSet<DeviceInstance>();
            this.ReservationLists = new HashSet<ReservationList>();
        }
    
        public int DeviceTypeId { get; set; }
        public string DevicaeName { get; set; }
        public string DeviceDescription { get; set; }
    
        public virtual ICollection<DeviceInstance> DeviceInstances { get; set; }
        public virtual ICollection<ReservationList> ReservationLists { get; set; }
    }
}
