//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PcPool.Inventory.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PcPoolEntities : DbContext
    {
        public PcPoolEntities()
            : base("name=PcPoolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DeviceInstance> DeviceInstances { get; set; }
        public DbSet<DeviceStatu> DeviceStatus { get; set; }
        public DbSet<DeviceType> DeviceTypes { get; set; }
        public DbSet<ReservationList> ReservationLists { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<UserType> UserTypes { get; set; }
    }
}
